config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  devise_for :users
  resources :users, only: [:show]
  resources :uploads
  resources :topics
  resources :concepts
  resources :exercises
  resources :roadmaps
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'

  post '/applications' => 'applications#create', as: 'applications'
  post '/course_ideas' => 'course_ideas#create', as: 'course_ideas'
  post '/contacts' => 'contacts#create', as: 'contacts'

  get '/courses' => 'pages#courses'
  get '/courses/html_1' => 'pages#html_1'
  get '/courses/rails_1' => 'pages#rails_1'
  get '/courses/game_dev_1' => 'pages#game_dev_1'
  get '/after_school' => 'pages#after_school', as: 'after_school'
  get '/our_program' => 'pages#our_program', as: 'our_program'
  get '/pricing' => 'pages#pricing'
  get '/about' => 'pages#about'
  get '/apply' => 'pages#apply'
  get '/privacy_policy' => 'pages#privacy_policy'

  resources :courses do
    resources :roadmaps
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application.rb
class Application < ActiveRecord::Base
  validates :student_first_name,
            :student_last_name,
            :student_email, presence: true

  validates :student_email,
            :parent_email, format: { :with => /@/ }, allow_blank: true

  belongs_to :course
  belongs_to :section
end

app/models/concept.rb
class Concept < ActiveRecord::Base
  belongs_to :roadmap
  belongs_to :topic
  acts_as_list scope: :topic
  has_many :exercises, -> { order(position: :asc) }

  def prev
    topic.concepts.find_by(position: position - 1)
  end

  def next
    topic.concepts.find_by(position: position + 1)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, format: { :with => /@/ }
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :sections
  belongs_to :track
  has_many :roadmaps

  def roadmap
    roadmaps.order('created_at asc').last
  end
end

app/models/course_idea.rb
class CourseIdea < ActiveRecord::Base
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :user
  belongs_to :section

  def roadmap
    section.roadmap
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :concept
  acts_as_list scope: :concept
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
  belongs_to :course
  has_many :topics, -> { order(position: :asc) }
  has_many :concepts
end

app/models/section.rb
class Section < ActiveRecord::Base
  self.skip_time_zone_conversion_for_attributes = [:start_date_time]

  belongs_to :course

  delegate :roadmap, :to => :course

  def formatted_timeframe
    "#{formatted_date(start_date_time)} to #{formatted_date(start_date_time + course.weeks.weeks)} on #{start_date_time.strftime('%A')}s at #{start_date_time.strftime('%l:%M %p CST')}"
  end

  def with_course
    "#{course.name} - #{formatted_timeframe}"
  end

  private
    def formatted_date(time)
      time
        .in_time_zone("Central Time (US & Canada)")
        .strftime('%b %d %Y')
    end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :roadmap
  acts_as_list scope: :roadmap
  has_many :concepts, -> { order(position: :asc) }
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :courses
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  mount_uploader :file, FileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :enrollments
end

app/controllers/topics_controller.rb
class TopicsController < InheritedResources::Base

  private

    def topic_params
      params.require(:topic).permit(:name, :roadmap_id, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/roadmaps_helper.rb
module RoadmapsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :roadmap_id %><br>
    <%= f.collection_select :roadmap_id, Roadmap.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Roadmap</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.roadmap_id %></td>
        <td><%= topic.position %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Roadmap:</strong>
  <%= @topic.roadmap_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @topic.position %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>