config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  devise_for :users
  resources :users, only: [:show]
  resources :uploads
  resources :topics
  resources :concepts
  resources :exercises
  resources :roadmaps
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'

  post '/applications' => 'applications#create', as: 'applications'
  post '/course_ideas' => 'course_ideas#create', as: 'course_ideas'
  post '/contacts' => 'contacts#create', as: 'contacts'

  get '/courses' => 'pages#courses'
  get '/courses/html_1' => 'pages#html_1'
  get '/courses/rails_1' => 'pages#rails_1'
  get '/courses/game_dev_1' => 'pages#game_dev_1'
  get '/after_school' => 'pages#after_school', as: 'after_school'
  get '/our_program' => 'pages#our_program', as: 'our_program'
  get '/pricing' => 'pages#pricing'
  get '/about' => 'pages#about'
  get '/apply' => 'pages#apply'
  get '/privacy_policy' => 'pages#privacy_policy'

  resources :courses do
    resources :roadmaps
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application.rb
class Application < ActiveRecord::Base
  validates :student_first_name,
            :student_last_name,
            :student_email, presence: true

  validates :student_email,
            :parent_email, format: { :with => /@/ }, allow_blank: true

  belongs_to :course
  belongs_to :section
end

app/models/concept.rb
class Concept < ActiveRecord::Base
  belongs_to :roadmap
  belongs_to :topic
  acts_as_list scope: :topic
  has_many :exercises, -> { order(position: :asc) }

  def prev
    topic.concepts.find_by(position: position - 1)
  end

  def next
    topic.concepts.find_by(position: position + 1)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, format: { :with => /@/ }
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :sections
  belongs_to :track
  has_many :roadmaps

  def roadmap
    roadmaps.order('created_at asc').last
  end
end

app/models/course_idea.rb
class CourseIdea < ActiveRecord::Base
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :user
  belongs_to :section

  def roadmap
    section.roadmap
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :concept
  acts_as_list scope: :concept
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
  belongs_to :course
  has_many :topics, -> { order(position: :asc) }
  has_many :concepts
end

app/models/section.rb
class Section < ActiveRecord::Base
  self.skip_time_zone_conversion_for_attributes = [:start_date_time]

  belongs_to :course

  delegate :roadmap, :to => :course

  def formatted_timeframe
    "#{formatted_date(start_date_time)} to #{formatted_date(start_date_time + course.weeks.weeks)} on #{start_date_time.strftime('%A')}s at #{start_date_time.strftime('%l:%M %p CST')}"
  end

  def with_course
    "#{course.name} - #{formatted_timeframe}"
  end

  private
    def formatted_date(time)
      time
        .in_time_zone("Central Time (US & Canada)")
        .strftime('%b %d %Y')
    end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :roadmap
  acts_as_list scope: :roadmap
  has_many :concepts, -> { order(position: :asc) }
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :courses
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  mount_uploader :file, FileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :enrollments
end

app/controllers/concepts_controller.rb
class ConceptsController < InheritedResources::Base

  def show
    @concept = Concept.find(params[:id])
    @roadmap = @concept.roadmap
  end

  private

    def concept_params
      params.require(:concept).permit(:roadmap_id, :topic_id, :position, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/roadmaps_helper.rb
module RoadmapsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/concepts/_form.html.erb
<%= form_for(@concept) do |f| %>
  <% if @concept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

      <ul>
      <% @concept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :roadmap_id %><br>
    <%= f.collection_select :roadmap_id, Roadmap.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :topic_id %><br>
    <%= f.collection_select :topic_id, Topic.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concepts/edit.html.erb
<h1>Editing Concept</h1>

<%= render 'form' %>

<%= link_to 'Show', @concept %> |
<%= link_to 'Back', concepts_path %>

app/views/concepts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Concepts</h1>

<table>
  <thead>
    <tr>
      <th>Roadmap</th>
      <th>Topic</th>
      <th>Position</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= concept.roadmap_id %></td>
        <td><%= concept.topic_id %></td>
        <td><%= concept.position %></td>
        <td><%= concept.title %></td>
        <td><%= concept.content %></td>
        <td><%= link_to 'Show', concept %></td>
        <td><%= link_to 'Edit', edit_concept_path(concept) %></td>
        <td><%= link_to 'Destroy', concept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concept', new_concept_path %>

app/views/concepts/new.html.erb
<h1>New Concept</h1>

<%= render 'form' %>

<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<div class="container">
  <h1><%= @roadmap.course.name %></h1>
  <div class="row">
    <div class="col-md-3 impt-copy">
      <%= render 'roadmaps/roadmap_links', roadmap: @roadmap %>
    </div>
    <div class="col-md-6 col-md-offset-1">

      <h2 class="topic-heading"><%= @concept.topic.name %></h2>
      <a id="concept-<%= @concept.id %>" class="anchor"></a>
      <div class="full-concept">
        <div class="panel panel-default">
          <div class="panel-body concept-card">
            <h3 class="media-heading"><%= @concept.title %></h3>
            <%= @concept.content.html_safe %>
          </div>
        </div>
        <% @concept.exercises.each do |exercise| %>
          <div class="vert-line"></div>
          <div class="panel panel-default">
            <div class="panel-body">
              <h4 class="media-heading">Exercise <%= exercise.position %> - <%= exercise.concept.title %></h4>
              <p><%= exercise.description %></p>
              <%= link_to exercise.url, exercise.url, target: '_blank' %>
            </div>
          </div>
        <% end %>
      </div>
      <% if @concept.prev.present? %>
        <%= link_to "<< Previous concept", concept_path(@concept.prev), class: "prev-concept-link" %>
      <% end %>
      <% if @concept.next.present? %>
        <%= link_to "Next concept >>", concept_path(@concept.next), class: "next-concept-link" %>
      <% end %>
    </div>
  </div>
</div>